# experiment_config.yaml

experiment_name: "baseline_model"

data:
  # Paths to your data files
  train_data_path: "path/to/train/data.csv"
  test_data_path: "path/to/test/data.csv"
  # Features configuration
  features:
    numeric:
      - "age"
      - "salary"
      - "years_of_experience"
    categorical:
      - "job_role"
      - "education_level"
      - "department"
  # Specify features to exclude, if any
  exclude_features:
    - "id"
    - "timestamp"

model:
  # Model type can be customized (e.g., "DNN", "linear", "wide_and_deep")
  type: "DNN"
  parameters:
    learning_rate: 0.001
    batch_size: 32
    epochs: 10
    hidden_units: [64, 32]  # List of integers for the size of each hidden layer

training:
  # Training specific configurations
  validation_split: 0.2
  early_stopping:
    enabled: true
    patience: 3

evaluation:
  # Configuration for evaluating the model
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
