experiment_name: "baseline_model"

data:
  # Paths to data files
  train_data_path: "data/train.csv"
  test_data_path: "data/test.csv"
  # Features configuration
  features:
    numeric:
      - "PassengerId"
      - "Pclass"
      - "Age"
      - "SibSp"
      - "Parch"
      - "Fare"
    categorical:
      - "Sex"
      - "Cabin"
      - "Embarked"
    text:
      - "Name"
      - "Ticket"
  target:
    - "Survived"

model:
  type: "DNN" # e.g., "DNN", "linear", "wide_and_deep"
  parameters:
    learning_rate: 0.001
    batch_size: 32
    epochs: 10
    hidden_units: [64, 32]  # List of integers for the size of each hidden layer

training:
  # Training specific configurations
  validation_split: 0.2
  early_stopping:
    enabled: true
    patience: 3

evaluation:
  # Configuration for evaluating the model
  metrics:
    - "accuracy"
    - "precision"
    - "recall"