update-requirements:
	python3 -m pip install -r requirements.txt
	pre-commit install

load_data:
	python3 src.load_data

preprocessing:
	python3 -m src.preprocessing

modeling:
	python3 src.modeling

profiling:
	python3 src.profiling
